### ISSUE TITLE
Internal Server Error When Certificate is Revoked

### ISSUE THREAD

**Issue by mattbodholdt** [mattbodholdt/openca-ocspd#2]
In v2 Docker Hub image, when a request is made for a certificate which has been revoked , the server will respond status code 200 and return an internal server error.  Requests for valid certificates are served successfully.

```bash
OCSP Request Data:
    Version: 1 (0x0)
    Requestor List:
        Certificate ID:
          Hash Algorithm: sha1
          Issuer Name Hash: 94F75A698288B2DC7BA1EA132AF9465A9EDF9599
          Issuer Key Hash: 596D0C6520A05F2F2989D43259870B016F821E60
          Serial Number: 1001
Responder Error: internalerror (2)
```

The container logs:
```bash
Apr 18 15:36:44 2019 GMT [1] ERROR: [pki_ocsp_resp.c:200] [ERROR] Can not create basic entry!
Apr 18 15:36:44 2019 GMT [1] ERROR: [response.c:458] [ERROR] Can not add a simple resp into the OCSP response
```

**Comment by BwackNinja** [comment]
Issue in openca-ocspd is https://github.com/openca/openca-ocspd/issues/31

Incorrect function used. After patching, it returns the proper response.

**Comment by mattbodholdt** [comment]
Thank you @BwackNinja.  The latest and v2 tags on the docker image work now after forking openca/openca-ocspd and making the change mentioned in openca/openca-ocspd#31
